### ISSUE TITLE
Pipeline failing on terraform output

### ISSUE THREAD

**Issue by vanneback** [elastisys/ck8s-cluster#50] opened 2020-09-23 09:59 UTC
Seen this error in a few runs now.  this from run https://github.com/elastisys/ck8s-apps/pull/86/checks?check_run_id=1154055888

```
2020-09-23T09:29:17.2124278Z Outputs:
2020-09-23T09:29:17.2124887Z 
2020-09-23T09:29:17.2126685Z domain_name = ck8s-apps-exoscale-dev-268445954.a1ck.io
2020-09-23T09:29:17.2128440Z sc_control_plane_lb_ip_address = 194.182.163.202
2020-09-23T09:29:17.2129694Z sc_dns_name = [
2020-09-23T09:29:17.2131424Z   "*.ops.ck8s-apps-exoscale-dev-268445954.a1ck.io",
2020-09-23T09:29:17.2135262Z   "dex.ck8s-apps-exoscale-dev-268445954.a1ck.io",
2020-09-23T09:29:17.2137540Z   "grafana.ck8s-apps-exoscale-dev-268445954.a1ck.io",
2020-09-23T09:29:17.2151894Z   "harbor.ck8s-apps-exoscale-dev-268445954.a1ck.io",
2020-09-23T09:29:17.2154286Z   "kibana.ck8s-apps-exoscale-dev-268445954.a1ck.io",
2020-09-23T09:29:17.2156836Z   "notary.harbor.ck8s-apps-exoscale-dev-268445954.a1ck.io",
2020-09-23T09:29:17.2158733Z ]
2020-09-23T09:29:17.2160034Z sc_ingress_controller_lb_ip_address = 194.182.160.119
2020-09-23T09:29:17.2161428Z sc_master_ips = {
2020-09-23T09:29:17.2163440Z   "ck8s-apps-exoscale-dev-268445954-service-cluster-master-0" = {
2020-09-23T09:29:17.2165457Z     "private_ip" = "172.0.10.132"
2020-09-23T09:29:17.2166632Z     "public_ip" = "89.145.166.63"
2020-09-23T09:29:17.2167761Z   }
2020-09-23T09:29:17.2168808Z }
2020-09-23T09:29:17.2169864Z sc_nfs_ips = {
2020-09-23T09:29:17.2170951Z   "nfs" = {
2020-09-23T09:29:17.2172066Z     "private_ip" = "172.0.10.205"
2020-09-23T09:29:17.2173231Z     "public_ip" = "194.182.160.143"
2020-09-23T09:29:17.2174353Z   }
2020-09-23T09:29:17.2175413Z }
2020-09-23T09:29:17.2176484Z sc_worker_ips = {
2020-09-23T09:29:17.2178491Z   "ck8s-apps-exoscale-dev-268445954-service-cluster-worker-0" = {
2020-09-23T09:29:17.2180399Z     "private_ip" = "172.0.10.59"
2020-09-23T09:29:17.2181568Z     "public_ip" = "194.182.160.133"
2020-09-23T09:29:17.2182773Z   }
2020-09-23T09:29:17.2184765Z   "ck8s-apps-exoscale-dev-268445954-service-cluster-worker-1" = {
2020-09-23T09:29:17.2186692Z     "private_ip" = "172.0.10.72"
2020-09-23T09:29:17.2187847Z     "public_ip" = "194.182.161.84"
2020-09-23T09:29:17.2189576Z   }
2020-09-23T09:29:17.2190637Z }
2020-09-23T09:29:17.2191783Z wc_control_plane_lb_ip_address = 194.182.163.27
2020-09-23T09:29:17.2193018Z wc_dns_name = [
2020-09-23T09:29:17.2194716Z   "*.ck8s-apps-exoscale-dev-268445954.a1ck.io",
2020-09-23T09:29:17.2197096Z   "prometheus.ops.ck8s-apps-exoscale-dev-268445954.a1ck.io",
2020-09-23T09:29:17.2199071Z ]
2020-09-23T09:29:17.2200259Z wc_ingress_controller_lb_ip_address = 194.182.162.22
2020-09-23T09:29:17.2206106Z wc_master_ips = {
2020-09-23T09:29:17.2208767Z   "ck8s-apps-exoscale-dev-268445954-workload-cluster-master-0" = {
2020-09-23T09:29:17.2211789Z     "private_ip" = "172.0.10.132"
2020-09-23T09:29:17.2215654Z 2020-09-23T09:29:17.214Z	[35mDEBUG[0m	runner/terraform.go:161	terraform_output	{"config": {"path": "/__w/ck8s-apps/ck8s-apps/ck8s-cluster/terraform/exoscale", "workspace": "ck8s-apps-exoscale-dev-268445954", "data_dir": "/ck8s-config/.state/.terraform", "state": "", "backend_config": "/ck8s-config/backend_config.hcl", "tfvars": "/ck8s-config/config.tfvars"}}
2020-09-23T09:29:17.2219460Z 2020-09-23T09:29:17.214Z	[35mDEBUG[0m	runner/standard.go:52	standard_runner_background	{"cmd": {"name": "terraform"}}
2020-09-23T09:29:17.2221911Z 2020-09-23T09:29:17.214Z	[35mDEBUG[0m	runner/standard.go:115	standard_runner_output_handler
2020-09-23T09:29:17.2223614Z     "public_ip" = "194.182.162.88"
2020-09-23T09:29:17.2224744Z   }
2020-09-23T09:29:17.2225777Z }
2020-09-23T09:29:17.2226843Z wc_nfs_ips = {
2020-09-23T09:29:17.2228002Z   "nfs" = {
2020-09-23T09:29:17.2229303Z     "private_ip" = "172.0.10.205"
2020-09-23T09:29:17.2230528Z     "public_ip" = "194.182.161.186"
2020-09-23T09:29:17.2231752Z   }
2020-09-23T09:29:17.2232979Z }
2020-09-23T09:29:17.2234154Z wc_worker_ips = {
2020-09-23T09:29:17.2236319Z   "ck8s-apps-exoscale-dev-268445954-workload-cluster-worker-0" = {
2020-09-23T09:29:17.2238336Z     "private_ip" = "172.0.10.72"
2020-09-23T09:29:17.2239651Z     "public_ip" = "194.182.162.233"
2020-09-23T09:29:17.2240803Z   }
2020-09-23T09:29:17.2242007Z }[0m
2020-09-23T09:29:27.3890057Z Error: error outputting Terraform config: error while executing `terraform output -json`: 2 errors occurred:
2020-09-23T09:29:27.3892203Z 	* EOF
2020-09-23T09:29:27.3897296Z 	* exit status 1
```

**Comment by simonklb** [comment] 2020-09-23 10:47
Looks like a race. The `terraform apply` seems to return before it's completed and then `terraform output` doesn't return anything. Notice how the output after `terraform apply` continues while the `terraform output` starts:
```
2020-09-23T09:29:17.2206106Z wc_master_ips = {
2020-09-23T09:29:17.2208767Z   "ck8s-apps-exoscale-dev-268445954-workload-cluster-master-0" = {
2020-09-23T09:29:17.2211789Z     "private_ip" = "172.0.10.132"
2020-09-23T09:29:17.2215654Z 2020-09-23T09:29:17.214Z	�[35mDEBUG�[0m	runner/terraform.go:161	terraform_output	{"config": {"path": "/__w/ck8s-apps/ck8s-apps/ck8s-cluster/terraform/exoscale", "workspace": "ck8s-apps-exoscale-dev-268445954", "data_dir": "/ck8s-config/.state/.terraform", "state": "", "backend_config": "/ck8s-config/backend_config.hcl", "tfvars": "/ck8s-config/config.tfvars"}}
2020-09-23T09:29:17.2219460Z 2020-09-23T09:29:17.214Z	�[35mDEBUG�[0m	runner/standard.go:52	standard_runner_background	{"cmd": {"name": "terraform"}}
2020-09-23T09:29:17.2221911Z 2020-09-23T09:29:17.214Z	�[35mDEBUG�[0m	runner/standard.go:115	standard_runner_output_handler
2020-09-23T09:29:17.2223614Z     "public_ip" = "194.182.162.88"
2020-09-23T09:29:17.2224744Z   }
2020-09-23T09:29:17.2225777Z }
```

Can't say for sure though, needs some further digging.

**Comment by simonklb** [comment] 2020-09-24 10:03
Almost positive this is a duplicate of https://github.com/elastisys/ck8s-cluster/issues/18

The reason why you don't see the stderr output is because the apps pipeline is not running against a branch that has this fix: https://github.com/elastisys/ck8s-cluster/commit/029820935243c0a95784aca9145eafce8ca356c4

**Closed as completed by simonklb** 2020-09-24 10:03 UTC
Labels: pipeline
